USE CSE_3A_106
--1
SELECT * FROM DEPOSIT

--2
SELECT * FROM BORROW

--3
SELECT * FROM CUSTOMERS

--4
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT

--5
SELECT LOANNO,AMOUNT FROM BORROW

--6
SELECT LOANNO FROM BORROW WHERE BNAME='ANDHERI'

--7
SELECT ACTNO,AMOUNT FROM DEPOSIT WHERE ACTNO=106

--8
SELECT BNAME FROM BORROW WHERE AMOUNT>5000

--9
SELECT CNAME FROM DEPOSIT WHERE ADATE>'1996-12-01'

--10
SELECT CNAME FROM DEPOSIT WHERE ACTNO<105

--11
SELECT CNAME FROM CUSTOMERS WHERE CITY='NAGPUR' OR CITY='DELHI'

SELECT CNAME FROM CUSTOMERS WHERE CITY IN ('NAGPUR','DELHI')

--12
SELECT BNAME,CNAME FROM DEPOSIT WHERE AMOUNT>4000 AND ACTNO<150

--13
SELECT CNAME FROM BORROW WHERE AMOUNT>=3000 AND AMOUNT<=8000

SELECT CNAME FROM BORROW WHERE AMOUNT BETWEEN 3000 AND 8000

--14
SELECT * FROM DEPOSIT WHERE BNAME != 'ANDHERI'

SELECT * FROM DEPOSIT WHERE BNAME <> 'ANDHERI'

--15
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT WHERE (BNAME = 'AJNI' OR BNAME='KAROLBAGH' OR BNAME='M.G.ROAD') AND ACTNO<104

SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT WHERE (BNAME IN ('AJNI','KAROLBAGH','M.G.ROAD')) AND ACTNO<104